# Memoire volontairement basse : AndroidIDE compile sur telephone.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
# compileSdk 35 avec AGP 8.1 : avertissement connu et sans consequence.
android.suppressUnsupportedCompileSdk=35
